name: Decommission Hub
description: Track the decommissioning of a hub
title: "[Decommission Hub] {{hub_name}}"
body:
  - type: input
    id: new_hub_issue_link
    attributes:
      label: Link to New Hub issue
      description: The link to the original issue to create the hub, e.g. https://github.com/2i2c-org/infrastructure/issues/#NNN
      placeholder: https://github.com/2i2c-org/infrastructure/issues/#NNN
    validations:
      required: true
  - type: input
    id: proposed_end_date
    attributes:
      label: Proposed end date
      description: The date by which the hub should be out of service. This should have been mentioned in the New Hub issue above so can be copy-pasted. Otherwise, leave blank and negotiate with the Community Representative.
      placeholder: YYYY-MM-DD
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ### Task List
        #### Phase I
  - type: checkboxes
    id: phase_i_tasks
    attributes:
      label: Phase I Tasks
      description: Confirm with Community Representative that the hub is no longer in use and it's safe to decommission
      options:
        - label: Confirm with Community Representative that the hub is no longer in use and it's safe to decommission
          required: false
  - type: markdown
    attributes:
      value: |
        #### Phase II
  - type: checkboxes
    id: phase_ii_tasks
    attributes:
      label: Phase II Tasks
      options:
        - label: Manage existing home directory data (migrate data from the hub or delete it)
          required: false
        - label: Manage existing cloud bucket data (migrate data, or delete it)
          required: false
        - label: Delete the hub's authentication application on GitHub or CILogon (note CILogon removal requires the hub config in place)
          required: false
  - type: markdown
    attributes:
      value: |
        #### Phase III - Cluster Removal
        _This phase is only necessary for single hub clusters._
  - type: checkboxes
    id: phase_iii_tasks
    attributes:
      label: Phase III Tasks
      options:
        - label: "Remove the cluster's datasource from the central Grafana with:"
          required: false
        - label: "deployer grafana central-ds remove <cluster_name>"
          required: false
        - label: "Remove the appropriate `config/clusters/<cluster_name>/<hub_name>.values.yaml` files. A complete list of relevant files can be found under the appropriate entry in the associated `cluster.yaml` file."
          required: false
        - label: "Remove the associated hub entry from the `config/clusters/<cluster_name>/cluster.yaml` file."
          required: false
        - label: "Remove the hub deployment"
          required: false
        - label: "helm --namespace HUB_NAME delete HUB_NAME"
          required: false
        - label: "kubectl delete namespace HUB_NAME"
          required: false
        - label: "TIP: Run `deployer use-cluster-credentials <cluster_name>` before running the above commands"
          required: false
