name: Set proj status fields
on: 
  issues:
    types: [opened, reopened]

jobs:
  proj-fields:
    runs-on: ubuntu-latest
    steps:
      - uses: EndBug/project-fields@v2
        id: fields
        with:
          operation: set
          fields: Status
          github_token: ${{ secrets.PROJ_PAT }}
          project_url: https://github.com/users/GeorgianaElena/projects/3
          values: "Todo"
      - run: echo ${{ steps.fields.outputs.values }}
